### K-Nearest Neighbors

The algorithm find the nearest n number to the unknown X

In [1]:
import numpy as np

def kNN(Xtrain,ytrain,Xtest,k):
    yTest = []
    for x in Xtest:
        d = np.sqrt(np.sum((Xtrain-x)**2,axis = 1))
        idx = np.argsort(d)
        (values,counts) = np.unique(ytrain[idx[:k]],return_counts= True)
        ind = np.argmax(counts)
        ytest.append(values[ind])
    return ytest

In [15]:
import pandas as pd
iris = pd.read_csv('iris.csv',header = None,names=['a','b','c','d','label'])

In [16]:
iris.head()

a    b    c    d        label
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [23]:
X = iris.drop(columns= 'label').values
y = iris['label']

In [31]:
def split_train_test(data,ratio):
    train = list()
    test  = list()
    train_size = ratio*list(dataset)
    test_size =  (1-ratio)*list(dataset)
    

In [37]:
np.unique(iris['label'])

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [40]:
np.where(iris['label']=='Iris-versicolor')

(array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       dtype=int64),)

In [41]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
a        150 non-null float64
b        150 non-null float64
c        150 non-null float64
d        150 non-null float64
label    150 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB


In [47]:
a = [[1,1,3,9,14,23,14,15,36,4]]

In [49]:
np.random.rand(len(iris))

array([0.11941422, 0.78279203, 0.26802373, 0.26706293, 0.72021275,
       0.07824078, 0.03786059, 0.58035898, 0.96475965, 0.25644072,
       0.13843277, 0.19531138, 0.37207782, 0.13701693, 0.33977952,
       0.31189862, 0.94089714, 0.38772278, 0.39366434, 0.57296663,
       0.65484778, 0.32946171, 0.43570124, 0.55750266, 0.02088902,
       0.96973296, 0.43619394, 0.04937048, 0.65963349, 0.79024596,
       0.57439433, 0.07169497, 0.01846482, 0.12175723, 0.43412058,
       0.16247034, 0.14617602, 0.80003178, 0.11519644, 0.65369709,
       0.92223143, 0.36282729, 0.05115678, 0.60892093, 0.69957247,
       0.24069859, 0.17707982, 0.27325553, 0.09659027, 0.85118933,
       0.0026151 , 0.31369343, 0.84396163, 0.36702801, 0.53508107,
       0.0973655 , 0.72129569, 0.30417719, 0.68098032, 0.68623148,
       0.7318166 , 0.83474307, 0.04207156, 0.16452831, 0.1158827 ,
       0.67145636, 0.43116186, 0.68902295, 0.89082707, 0.83525383,
       0.4834604 , 0.10774925, 0.01861358, 0.01857488, 0.98772

In [58]:
a = np.argsort(range(len(iris)))

In [62]:
np.random.shuffle(a)

In [64]:
a*0.6

array([11.4, 17.4, 54. , 46.2, 64.2, 82.2, 61.2, 15.6, 12.6, 31.8, 40.8,
       60.6, 63.6, 25.8, 46.8, 78. , 87.6, 49.8, 44.4, 62.4, 26.4, 85.8,
       68.4, 69.6, 37.2,  0. , 16.2, 48. , 31.2, 86.4, 35.4, 81. , 24. ,
       29.4, 23.4,  4.2, 42. , 34.2, 21. , 33. , 57. , 19.2, 39.6, 34.8,
       47.4, 27.6,  8.4, 67.2, 22.8, 14.4,  9.6, 77.4,  9. , 71.4, 66. ,
       43.2, 40.2, 87. , 10.2, 74.4, 58.8, 22.2, 45.6, 36. , 51.6, 20.4,
       78.6, 51. , 84.6,  6.6, 28.2, 52.2, 33.6, 67.8, 82.8, 80.4, 16.8,
        3.6, 50.4, 19.8, 58.2, 76.8, 30. , 70.8, 65.4, 12. ,  3. , 30.6,
       72. , 39. , 25.2, 24.6, 66.6, 52.8, 59.4, 60. , 55.8,  5.4, 85.2,
       13.8, 63. , 76.2,  1.8, 83.4, 79.8, 37.8, 45. , 28.8, 57.6, 15. ,
        7.2, 27. , 48.6, 64.8, 42.6, 43.8,  7.8,  2.4, 32.4, 36.6, 89.4,
       75. , 79.2, 81.6, 84. , 69. , 75.6, 54.6, 70.2, 21.6, 18. , 73.2,
        0.6, 61.8, 10.8, 53.4, 41.4, 88.8,  1.2, 73.8, 88.2, 72.6,  6. ,
       49.2, 56.4,  4.8, 38.4, 18.6, 13.2, 55.2])