In [40]:
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import re
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from sklearn.preprocessing import OneHotEncoder
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [2]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [3]:
with open('moby_dick_four_chapters.txt') as file:
    texts = file.read()

In [5]:
texts

'Call me Ishmael.  Some years ago--never mind how long\nprecisely--having little or no money in my purse, and nothing\nparticular to interest me on shore, I thought I would sail about a\nlittle and see the watery part of the world.  It is a way I have of\ndriving off the spleen and regulating the circulation.  Whenever I\nfind myself growing grim about the mouth; whenever it is a damp,\ndrizzly November in my soul; whenever I find myself involuntarily\npausing before coffin warehouses, and bringing up the rear of every\nfuneral I meet; and especially whenever my hypos get such an upper\nhand of me, that it requires a strong moral principle to prevent me\nfrom deliberately stepping into the street, and methodically knocking\npeople\'s hats off--then, I account it high time to get to sea as soon\nas I can.  This is my substitute for pistol and ball.  With a\nphilosophical flourish Cato throws himself upon his sword; I quietly\ntake to the ship.  There is nothing surprising in this.  If t

In [10]:
def text_process(text):
#   word = text.lower()
#   word = word.split()
    word = re.sub('[^A-za-z1-9]',' ',text)
    word = word.lower()
    word = word.split()
#     word = [words for words in word if words not in stopwords.words('english')]
#     word = [SnowballStemmer('english').stem(words) for words in word]
    word = ' '.join(word)
    return word

In [11]:
text_cleaned = text_process(texts)

In [12]:
token = word_tokenize(text_cleaned)

In [13]:
length = len(token)

In [14]:
words = list(set(token))

In [15]:
##create Word to index
word_idx = {}
for i,j in enumerate(words):
    word_idx[j]=i

In [16]:
## Create Index to word
idx_word = {}
num = 0
for i in word_idx:
    idx_word[num] = i
    num = num+1

In [17]:
word_to_generated = []
word_inputs = []
word_thredhold = 10
start_idx = 0
for i in range(word_thredhold,length):
    word_inputs.append(token[start_idx:i+1])
#     word_to_generated.append(token[i+1-word_thredhold:])
    start_idx = start_idx+1

In [18]:
" ".join(word_inputs[0])

'call me ishmael some years ago never mind how long precisely'

In [19]:
" ".join(word_inputs[1])

'me ishmael some years ago never mind how long precisely having'

In [20]:
" ".join(word_inputs[-1])

'monkey jacket and sporting his harpoon like a marshal s baton'

In [21]:
a = " ".join(word_inputs[0])

## Create X , y

In [22]:
tokenizer = Tokenizer()

In [23]:
tokenizer.fit_on_texts(text_cleaned.split())
num_word = len(tokenizer.word_index)
seq = tokenizer.texts_to_sequences(word_inputs)

In [24]:
tokenizer.word_index

{'the': 1,
 'a': 2,
 'and': 3,
 'of': 4,
 'i': 5,
 'to': 6,
 'in': 7,
 'it': 8,
 'that': 9,
 'he': 10,
 'his': 11,
 'was': 12,
 'but': 13,
 'me': 14,
 'with': 15,
 'as': 16,
 'you': 17,
 'this': 18,
 'at': 19,
 'is': 20,
 'all': 21,
 'my': 22,
 'for': 23,
 's': 24,
 'on': 25,
 'be': 26,
 'from': 27,
 'there': 28,
 'not': 29,
 'one': 30,
 'up': 31,
 'what': 32,
 'him': 33,
 'so': 34,
 'bed': 35,
 'no': 36,
 'now': 37,
 'about': 38,
 'into': 39,
 'or': 40,
 'by': 41,
 'were': 42,
 'out': 43,
 'harpooneer': 44,
 'had': 45,
 'then': 46,
 'have': 47,
 'an': 48,
 'some': 49,
 'little': 50,
 'upon': 51,
 'like': 52,
 'old': 53,
 'if': 54,
 'they': 55,
 't': 56,
 'landlord': 57,
 'over': 58,
 'thought': 59,
 'room': 60,
 'would': 61,
 'when': 62,
 'here': 63,
 'head': 64,
 'night': 65,
 'such': 66,
 'which': 67,
 'man': 68,
 'could': 69,
 'sea': 70,
 'though': 71,
 'time': 72,
 'do': 73,
 'said': 74,
 'other': 75,
 'very': 76,
 'go': 77,
 'these': 78,
 'more': 79,
 'did': 80,
 'first': 81,
 's

In [25]:
## this is an array for text sequence
np.array(word_inputs)

array([['call', 'me', 'ishmael', ..., 'how', 'long', 'precisely'],
       ['me', 'ishmael', 'some', ..., 'long', 'precisely', 'having'],
       ['ishmael', 'some', 'years', ..., 'precisely', 'having', 'little'],
       ...,
       ['great', 'pilot', 'monkey', ..., 'like', 'a', 'marshal'],
       ['pilot', 'monkey', 'jacket', ..., 'a', 'marshal', 's'],
       ['monkey', 'jacket', 'and', ..., 'marshal', 's', 'baton']],
      dtype='<U17')

### we actually want X as below cell

In [26]:
np.array(word_inputs)[:,:-1]

array([['call', 'me', 'ishmael', ..., 'mind', 'how', 'long'],
       ['me', 'ishmael', 'some', ..., 'how', 'long', 'precisely'],
       ['ishmael', 'some', 'years', ..., 'long', 'precisely', 'having'],
       ...,
       ['great', 'pilot', 'monkey', ..., 'harpoon', 'like', 'a'],
       ['pilot', 'monkey', 'jacket', ..., 'like', 'a', 'marshal'],
       ['monkey', 'jacket', 'and', ..., 'a', 'marshal', 's']],
      dtype='<U17')

In [27]:
X = np.array(seq)[:,:-1]
X

array([[ 558,   14,  222, ...,  197,  121,  104],
       [  14,  222,   49, ...,  121,  104,  559],
       [ 222,   49,  223, ...,  104,  559,  224],
       ...,
       [ 108, 2693,  520, ...,  243,   52,    2],
       [2693,  520,  883, ...,   52,    2, 2695],
       [ 520,  883,    3, ...,    2, 2695,   24]])

In [28]:
np.array(word_inputs)[:,-1]

array(['precisely', 'having', 'little', ..., 'marshal', 's', 'baton'],
      dtype='<U17')

In [29]:
y = np.array(seq)[:,-1]
y = tf.keras.utils.to_categorical(y,num_classes=num_word+1)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

## Create Model

In [30]:
model = tf.keras.models.Sequential([tf.keras.layers.Embedding(num_word,256,input_length=11),
                                   tf.keras.layers.LSTM(150,return_sequences=True),
                                   tf.keras.layers.LSTM(150),
                                   tf.keras.layers.Dense(150),
                                   tf.keras.layers.Dense(num_word+1,activation='softmax')])
model.compile(optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),
             loss=tf.keras.losses.categorical_crossentropy,
             metrics = ['accuracy'])

In [31]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 11, 256)           690176    
_________________________________________________________________
lstm (LSTM)                  (None, 11, 150)           244200    
_________________________________________________________________
lstm_1 (LSTM)                (None, 150)               180600    
_________________________________________________________________
dense (Dense)                (None, 150)               22650     
_________________________________________________________________
dense_1 (Dense)              (None, 2697)              407247    
Total params: 1,544,873
Trainable params: 1,544,873
Non-trainable params: 0
_________________________________________________________________


In [32]:
model.fit(X, y, batch_size=128, epochs=300,verbose=1)

Epoch 1/300
89/89 [==============================] - 10s 19ms/step - loss: 6.7027 - accuracy: 0.0451
Epoch 2/300
89/89 [==============================] - 2s 18ms/step - loss: 6.1237 - accuracy: 0.0567
Epoch 3/300
89/89 [==============================] - 2s 18ms/step - loss: 5.8895 - accuracy: 0.0706
Epoch 4/300
89/89 [==============================] - 2s 18ms/step - loss: 5.6633 - accuracy: 0.0857
Epoch 5/300
89/89 [==============================] - 2s 17ms/step - loss: 5.4255 - accuracy: 0.1011
Epoch 6/300
89/89 [==============================] - 1s 17ms/step - loss: 5.2054 - accuracy: 0.1160
Epoch 7/300
89/89 [==============================] - 1s 17ms/step - loss: 4.9938 - accuracy: 0.1327
Epoch 8/300
89/89 [==============================] - 1s 16ms/step - loss: 4.7772 - accuracy: 0.1395
Epoch 9/300
89/89 [==============================] - 1s 17ms/step - loss: 4.5466 - accuracy: 0.1564
Epoch 10/300
89/89 [==============================] - 1s 17ms/step - loss: 4.3301 - accuracy: 0.172

In [33]:
model.save('Text_generation.h5')

In [34]:
import pickle
with open('tokenizer','wb') as file:
  pickle.dump(tokenizer,file)

In [104]:
def text_process2(text):
#   word = text.lower()
#   word = word.split()
    word = re.sub('[^A-za-z1-9]',' ',text)
    word = word.lower()
    word = word.split()
#     word = [words for words in word if words not in stopwords.words('english')]
#     word = [SnowballStemmer('english').stem(words) for words in word]
    # word = ' '.join(word)
    return word

In [191]:
def generate_text(model,tokenizer,seq_length,seed_text,num_of_gen):
  text_generated = text_process2(seed_text)

  for i in range(num_of_gen):
    encoding_text = tokenizer.texts_to_sequences(text_generated)[-1]

    pad_encode = pad_sequences([encoding_text],seq_length)

    predict_seq = model.predict(pad_encode)
    predict_text = np.argmax(predict_seq,axis=1)
    text_generated.append(tokenizer.index_word[predict_text[0]])
  return text_generated

In [192]:
seed_text = "I want to go to the sea and make some "
generate_text(model,tokenizer,11,seed_text,11)
# input_text = text_process2(seed_text)

['i',
 'want',
 'to',
 'go',
 'to',
 'the',
 'sea',
 'and',
 'make',
 'some',
 'arched',
 'way',
 'to',
 'it',
 'would',
 'i',
 'thought',
 'to',
 'it',
 'would',
 'i']

In [186]:
# input_text.append(tokenizer.index_word[predict_text[0]])

In [187]:
input_text


['i',
 'want',
 'to',
 'go',
 'to',
 'the',
 'sea',
 'and',
 'make',
 'some',
 'thump',
 'and',
 'our']

In [188]:
pad_encode

array([[[796],
        [  6],
        [ 77],
        [  6],
        [  1],
        [ 70],
        [  3],
        [158],
        [ 49],
        [651],
        [  3]]], dtype=int32)

In [184]:
pad_encode

array([[[  5],
        [796],
        [  6],
        [ 77],
        [  6],
        [  1],
        [ 70],
        [  3],
        [158],
        [ 49],
        [651]]], dtype=int32)

In [67]:
bb

['against', 'of', 'the', 'or', 'voyage', 'a', 'over', 'into', 'this', 'in']

In [68]:
" ".join(bb)

'against of the or voyage a over into this in'

In [79]:
seed_text = "Hello I want to go to the sea and make some"